# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: lipstick 1.0.0.pre ruby lib

Gem::Specification.new do |s|
  s.name = "lipstick"
  s.version = "1.0.0.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Piers Chambers"]
  s.date = "2014-11-27"
  s.description = "Unofficial ruby wrapper for the Lime Light CRM membership and transaction APIs"
  s.email = "piers@varyonic.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/lipstick.rb",
    "lib/lipstick/api/campaign_find_active_response.rb",
    "lib/lipstick/api/campaign_view_response.rb",
    "lib/lipstick/api/customer_find_active_product_response.rb",
    "lib/lipstick/api/new_order_response.rb",
    "lib/lipstick/api/order_find_response.rb",
    "lib/lipstick/api/order_find_updated_response.rb",
    "lib/lipstick/api/order_view_response.rb",
    "lib/lipstick/api/response.rb",
    "lib/lipstick/api/session.rb",
    "lipstick.gemspec",
    "test/helper.rb",
    "test/test_lipstick.rb",
    "test/test_order_view_response.rb"
  ]
  s.homepage = "http://github.com/varyonic/lipstick"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Unofficial ruby wrapper for the Lime Light CRM APIs."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

